/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SystemRouteImport } from './routes/system'
import { Route as ResendRouteImport } from './routes/resend'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as MetabolicHealthRouteImport } from './routes/metabolic-health'
import { Route as LongevityRouteImport } from './routes/longevity'
import { Route as HormonalHealthRouteImport } from './routes/hormonal-health'
import { Route as GutHealthRouteImport } from './routes/gut-health'
import { Route as Glp1RouteImport } from './routes/glp1'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CognitivePerformanceRouteImport } from './routes/cognitive-performance'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSubscribeRouteImport } from './routes/api/public/subscribe'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicResendLinksRouteImport } from './routes/api/public/resend-links'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const ResendRoute = ResendRouteImport.update({
  id: '/resend',
  path: '/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const MetabolicHealthRoute = MetabolicHealthRouteImport.update({
  id: '/metabolic-health',
  path: '/metabolic-health',
  getParentRoute: () => rootRouteImport,
} as any)
const LongevityRoute = LongevityRouteImport.update({
  id: '/longevity',
  path: '/longevity',
  getParentRoute: () => rootRouteImport,
} as any)
const HormonalHealthRoute = HormonalHealthRouteImport.update({
  id: '/hormonal-health',
  path: '/hormonal-health',
  getParentRoute: () => rootRouteImport,
} as any)
const GutHealthRoute = GutHealthRouteImport.update({
  id: '/gut-health',
  path: '/gut-health',
  getParentRoute: () => rootRouteImport,
} as any)
const Glp1Route = Glp1RouteImport.update({
  id: '/glp1',
  path: '/glp1',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CognitivePerformanceRoute = CognitivePerformanceRouteImport.update({
  id: '/cognitive-performance',
  path: '/cognitive-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubscribeRoute = ApiPublicSubscribeRouteImport.update({
  id: '/api/public/subscribe',
  path: '/api/public/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResendLinksRoute = ApiPublicResendLinksRouteImport.update({
  id: '/api/public/resend-links',
  path: '/api/public/resend-links',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/cognitive-performance': typeof CognitivePerformanceRoute
  '/faq': typeof FaqRoute
  '/glp1': typeof Glp1Route
  '/gut-health': typeof GutHealthRoute
  '/hormonal-health': typeof HormonalHealthRoute
  '/longevity': typeof LongevityRoute
  '/metabolic-health': typeof MetabolicHealthRoute
  '/refund': typeof RefundRoute
  '/resend': typeof ResendRoute
  '/system': typeof SystemRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/api/public/resend-links': typeof ApiPublicResendLinksRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/cognitive-performance': typeof CognitivePerformanceRoute
  '/faq': typeof FaqRoute
  '/glp1': typeof Glp1Route
  '/gut-health': typeof GutHealthRoute
  '/hormonal-health': typeof HormonalHealthRoute
  '/longevity': typeof LongevityRoute
  '/metabolic-health': typeof MetabolicHealthRoute
  '/refund': typeof RefundRoute
  '/resend': typeof ResendRoute
  '/system': typeof SystemRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/api/public/resend-links': typeof ApiPublicResendLinksRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/cognitive-performance': typeof CognitivePerformanceRoute
  '/faq': typeof FaqRoute
  '/glp1': typeof Glp1Route
  '/gut-health': typeof GutHealthRoute
  '/hormonal-health': typeof HormonalHealthRoute
  '/longevity': typeof LongevityRoute
  '/metabolic-health': typeof MetabolicHealthRoute
  '/refund': typeof RefundRoute
  '/resend': typeof ResendRoute
  '/system': typeof SystemRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/api/public/resend-links': typeof ApiPublicResendLinksRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/cognitive-performance'
    | '/faq'
    | '/glp1'
    | '/gut-health'
    | '/hormonal-health'
    | '/longevity'
    | '/metabolic-health'
    | '/refund'
    | '/resend'
    | '/system'
    | '/terms'
    | '/thank-you'
    | '/api/public/resend-links'
    | '/api/public/stripe-webhook'
    | '/api/public/subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/cognitive-performance'
    | '/faq'
    | '/glp1'
    | '/gut-health'
    | '/hormonal-health'
    | '/longevity'
    | '/metabolic-health'
    | '/refund'
    | '/resend'
    | '/system'
    | '/terms'
    | '/thank-you'
    | '/api/public/resend-links'
    | '/api/public/stripe-webhook'
    | '/api/public/subscribe'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/cognitive-performance'
    | '/faq'
    | '/glp1'
    | '/gut-health'
    | '/hormonal-health'
    | '/longevity'
    | '/metabolic-health'
    | '/refund'
    | '/resend'
    | '/system'
    | '/terms'
    | '/thank-you'
    | '/api/public/resend-links'
    | '/api/public/stripe-webhook'
    | '/api/public/subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CognitivePerformanceRoute: typeof CognitivePerformanceRoute
  FaqRoute: typeof FaqRoute
  Glp1Route: typeof Glp1Route
  GutHealthRoute: typeof GutHealthRoute
  HormonalHealthRoute: typeof HormonalHealthRoute
  LongevityRoute: typeof LongevityRoute
  MetabolicHealthRoute: typeof MetabolicHealthRoute
  RefundRoute: typeof RefundRoute
  ResendRoute: typeof ResendRoute
  SystemRoute: typeof SystemRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  ApiPublicResendLinksRoute: typeof ApiPublicResendLinksRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicSubscribeRoute: typeof ApiPublicSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resend': {
      id: '/resend'
      path: '/resend'
      fullPath: '/resend'
      preLoaderRoute: typeof ResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metabolic-health': {
      id: '/metabolic-health'
      path: '/metabolic-health'
      fullPath: '/metabolic-health'
      preLoaderRoute: typeof MetabolicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/longevity': {
      id: '/longevity'
      path: '/longevity'
      fullPath: '/longevity'
      preLoaderRoute: typeof LongevityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hormonal-health': {
      id: '/hormonal-health'
      path: '/hormonal-health'
      fullPath: '/hormonal-health'
      preLoaderRoute: typeof HormonalHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gut-health': {
      id: '/gut-health'
      path: '/gut-health'
      fullPath: '/gut-health'
      preLoaderRoute: typeof GutHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glp1': {
      id: '/glp1'
      path: '/glp1'
      fullPath: '/glp1'
      preLoaderRoute: typeof Glp1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cognitive-performance': {
      id: '/cognitive-performance'
      path: '/cognitive-performance'
      fullPath: '/cognitive-performance'
      preLoaderRoute: typeof CognitivePerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/subscribe': {
      id: '/api/public/subscribe'
      path: '/api/public/subscribe'
      fullPath: '/api/public/subscribe'
      preLoaderRoute: typeof ApiPublicSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resend-links': {
      id: '/api/public/resend-links'
      path: '/api/public/resend-links'
      fullPath: '/api/public/resend-links'
      preLoaderRoute: typeof ApiPublicResendLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CognitivePerformanceRoute: CognitivePerformanceRoute,
  FaqRoute: FaqRoute,
  Glp1Route: Glp1Route,
  GutHealthRoute: GutHealthRoute,
  HormonalHealthRoute: HormonalHealthRoute,
  LongevityRoute: LongevityRoute,
  MetabolicHealthRoute: MetabolicHealthRoute,
  RefundRoute: RefundRoute,
  ResendRoute: ResendRoute,
  SystemRoute: SystemRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  ApiPublicResendLinksRoute: ApiPublicResendLinksRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicSubscribeRoute: ApiPublicSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
