/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as MetabolicHealthRouteImport } from './routes/metabolic-health'
import { Route as LongevityRouteImport } from './routes/longevity'
import { Route as HormonalHealthRouteImport } from './routes/hormonal-health'
import { Route as GutHealthRouteImport } from './routes/gut-health'
import { Route as Glp1RouteImport } from './routes/glp1'
import { Route as FreeRecipesRouteImport } from './routes/free-recipes'
import { Route as CognitivePerformanceRouteImport } from './routes/cognitive-performance'
import { Route as BundleRouteImport } from './routes/bundle'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const MetabolicHealthRoute = MetabolicHealthRouteImport.update({
  id: '/metabolic-health',
  path: '/metabolic-health',
  getParentRoute: () => rootRouteImport,
} as any)
const LongevityRoute = LongevityRouteImport.update({
  id: '/longevity',
  path: '/longevity',
  getParentRoute: () => rootRouteImport,
} as any)
const HormonalHealthRoute = HormonalHealthRouteImport.update({
  id: '/hormonal-health',
  path: '/hormonal-health',
  getParentRoute: () => rootRouteImport,
} as any)
const GutHealthRoute = GutHealthRouteImport.update({
  id: '/gut-health',
  path: '/gut-health',
  getParentRoute: () => rootRouteImport,
} as any)
const Glp1Route = Glp1RouteImport.update({
  id: '/glp1',
  path: '/glp1',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeRecipesRoute = FreeRecipesRouteImport.update({
  id: '/free-recipes',
  path: '/free-recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const CognitivePerformanceRoute = CognitivePerformanceRouteImport.update({
  id: '/cognitive-performance',
  path: '/cognitive-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const BundleRoute = BundleRouteImport.update({
  id: '/bundle',
  path: '/bundle',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/bundle': typeof BundleRoute
  '/cognitive-performance': typeof CognitivePerformanceRoute
  '/free-recipes': typeof FreeRecipesRoute
  '/glp1': typeof Glp1Route
  '/gut-health': typeof GutHealthRoute
  '/hormonal-health': typeof HormonalHealthRoute
  '/longevity': typeof LongevityRoute
  '/metabolic-health': typeof MetabolicHealthRoute
  '/preview': typeof PreviewRoute
  '/system': typeof SystemRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/bundle': typeof BundleRoute
  '/cognitive-performance': typeof CognitivePerformanceRoute
  '/free-recipes': typeof FreeRecipesRoute
  '/glp1': typeof Glp1Route
  '/gut-health': typeof GutHealthRoute
  '/hormonal-health': typeof HormonalHealthRoute
  '/longevity': typeof LongevityRoute
  '/metabolic-health': typeof MetabolicHealthRoute
  '/preview': typeof PreviewRoute
  '/system': typeof SystemRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/bundle': typeof BundleRoute
  '/cognitive-performance': typeof CognitivePerformanceRoute
  '/free-recipes': typeof FreeRecipesRoute
  '/glp1': typeof Glp1Route
  '/gut-health': typeof GutHealthRoute
  '/hormonal-health': typeof HormonalHealthRoute
  '/longevity': typeof LongevityRoute
  '/metabolic-health': typeof MetabolicHealthRoute
  '/preview': typeof PreviewRoute
  '/system': typeof SystemRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/bundle'
    | '/cognitive-performance'
    | '/free-recipes'
    | '/glp1'
    | '/gut-health'
    | '/hormonal-health'
    | '/longevity'
    | '/metabolic-health'
    | '/preview'
    | '/system'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/bundle'
    | '/cognitive-performance'
    | '/free-recipes'
    | '/glp1'
    | '/gut-health'
    | '/hormonal-health'
    | '/longevity'
    | '/metabolic-health'
    | '/preview'
    | '/system'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/bundle'
    | '/cognitive-performance'
    | '/free-recipes'
    | '/glp1'
    | '/gut-health'
    | '/hormonal-health'
    | '/longevity'
    | '/metabolic-health'
    | '/preview'
    | '/system'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  BundleRoute: typeof BundleRoute
  CognitivePerformanceRoute: typeof CognitivePerformanceRoute
  FreeRecipesRoute: typeof FreeRecipesRoute
  Glp1Route: typeof Glp1Route
  GutHealthRoute: typeof GutHealthRoute
  HormonalHealthRoute: typeof HormonalHealthRoute
  LongevityRoute: typeof LongevityRoute
  MetabolicHealthRoute: typeof MetabolicHealthRoute
  PreviewRoute: typeof PreviewRoute
  SystemRoute: typeof SystemRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metabolic-health': {
      id: '/metabolic-health'
      path: '/metabolic-health'
      fullPath: '/metabolic-health'
      preLoaderRoute: typeof MetabolicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/longevity': {
      id: '/longevity'
      path: '/longevity'
      fullPath: '/longevity'
      preLoaderRoute: typeof LongevityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hormonal-health': {
      id: '/hormonal-health'
      path: '/hormonal-health'
      fullPath: '/hormonal-health'
      preLoaderRoute: typeof HormonalHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gut-health': {
      id: '/gut-health'
      path: '/gut-health'
      fullPath: '/gut-health'
      preLoaderRoute: typeof GutHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glp1': {
      id: '/glp1'
      path: '/glp1'
      fullPath: '/glp1'
      preLoaderRoute: typeof Glp1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-recipes': {
      id: '/free-recipes'
      path: '/free-recipes'
      fullPath: '/free-recipes'
      preLoaderRoute: typeof FreeRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cognitive-performance': {
      id: '/cognitive-performance'
      path: '/cognitive-performance'
      fullPath: '/cognitive-performance'
      preLoaderRoute: typeof CognitivePerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundle': {
      id: '/bundle'
      path: '/bundle'
      fullPath: '/bundle'
      preLoaderRoute: typeof BundleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  BundleRoute: BundleRoute,
  CognitivePerformanceRoute: CognitivePerformanceRoute,
  FreeRecipesRoute: FreeRecipesRoute,
  Glp1Route: Glp1Route,
  GutHealthRoute: GutHealthRoute,
  HormonalHealthRoute: HormonalHealthRoute,
  LongevityRoute: LongevityRoute,
  MetabolicHealthRoute: MetabolicHealthRoute,
  PreviewRoute: PreviewRoute,
  SystemRoute: SystemRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
