/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SundayPrepRouteImport } from './routes/sunday-prep'
import { Route as SnacksRouteImport } from './routes/snacks'
import { Route as SmoothiesRouteImport } from './routes/smoothies'
import { Route as RealFoodResetRouteImport } from './routes/real-food-reset'
import { Route as PlantBasedRouteImport } from './routes/plant-based'
import { Route as MetabolicResetRouteImport } from './routes/metabolic-reset'
import { Route as MetabolicHealthRouteImport } from './routes/metabolic-health'
import { Route as MensPerformanceRouteImport } from './routes/mens-performance'
import { Route as LunchRouteImport } from './routes/lunch'
import { Route as LongevityRouteImport } from './routes/longevity'
import { Route as HormonalHealthRouteImport } from './routes/hormonal-health'
import { Route as HomeOldRouteImport } from './routes/home-old'
import { Route as GutResetRouteImport } from './routes/gut-reset'
import { Route as GutHealthRouteImport } from './routes/gut-health'
import { Route as Glp1RouteImport } from './routes/glp1'
import { Route as FreeRecipesRouteImport } from './routes/free-recipes'
import { Route as FoodAsMedicineRouteImport } from './routes/food-as-medicine'
import { Route as FamilyDinnersRouteImport } from './routes/family-dinners'
import { Route as DinnerRouteImport } from './routes/dinner'
import { Route as DessertsRouteImport } from './routes/desserts'
import { Route as CognitivePerformanceRouteImport } from './routes/cognitive-performance'
import { Route as BundleRouteImport } from './routes/bundle'
import { Route as BreakfastRouteImport } from './routes/breakfast'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R20MinuteMealRouteImport } from './routes/20-minute-meal'
import { Route as R10MealBlueprintRouteImport } from './routes/10-meal-blueprint'
import { Route as IndexRouteImport } from './routes/index'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SundayPrepRoute = SundayPrepRouteImport.update({
  id: '/sunday-prep',
  path: '/sunday-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const SnacksRoute = SnacksRouteImport.update({
  id: '/snacks',
  path: '/snacks',
  getParentRoute: () => rootRouteImport,
} as any)
const SmoothiesRoute = SmoothiesRouteImport.update({
  id: '/smoothies',
  path: '/smoothies',
  getParentRoute: () => rootRouteImport,
} as any)
const RealFoodResetRoute = RealFoodResetRouteImport.update({
  id: '/real-food-reset',
  path: '/real-food-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantBasedRoute = PlantBasedRouteImport.update({
  id: '/plant-based',
  path: '/plant-based',
  getParentRoute: () => rootRouteImport,
} as any)
const MetabolicResetRoute = MetabolicResetRouteImport.update({
  id: '/metabolic-reset',
  path: '/metabolic-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const MetabolicHealthRoute = MetabolicHealthRouteImport.update({
  id: '/metabolic-health',
  path: '/metabolic-health',
  getParentRoute: () => rootRouteImport,
} as any)
const MensPerformanceRoute = MensPerformanceRouteImport.update({
  id: '/mens-performance',
  path: '/mens-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const LunchRoute = LunchRouteImport.update({
  id: '/lunch',
  path: '/lunch',
  getParentRoute: () => rootRouteImport,
} as any)
const LongevityRoute = LongevityRouteImport.update({
  id: '/longevity',
  path: '/longevity',
  getParentRoute: () => rootRouteImport,
} as any)
const HormonalHealthRoute = HormonalHealthRouteImport.update({
  id: '/hormonal-health',
  path: '/hormonal-health',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeOldRoute = HomeOldRouteImport.update({
  id: '/home-old',
  path: '/home-old',
  getParentRoute: () => rootRouteImport,
} as any)
const GutResetRoute = GutResetRouteImport.update({
  id: '/gut-reset',
  path: '/gut-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const GutHealthRoute = GutHealthRouteImport.update({
  id: '/gut-health',
  path: '/gut-health',
  getParentRoute: () => rootRouteImport,
} as any)
const Glp1Route = Glp1RouteImport.update({
  id: '/glp1',
  path: '/glp1',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeRecipesRoute = FreeRecipesRouteImport.update({
  id: '/free-recipes',
  path: '/free-recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodAsMedicineRoute = FoodAsMedicineRouteImport.update({
  id: '/food-as-medicine',
  path: '/food-as-medicine',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyDinnersRoute = FamilyDinnersRouteImport.update({
  id: '/family-dinners',
  path: '/family-dinners',
  getParentRoute: () => rootRouteImport,
} as any)
const DinnerRoute = DinnerRouteImport.update({
  id: '/dinner',
  path: '/dinner',
  getParentRoute: () => rootRouteImport,
} as any)
const DessertsRoute = DessertsRouteImport.update({
  id: '/desserts',
  path: '/desserts',
  getParentRoute: () => rootRouteImport,
} as any)
const CognitivePerformanceRoute = CognitivePerformanceRouteImport.update({
  id: '/cognitive-performance',
  path: '/cognitive-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const BundleRoute = BundleRouteImport.update({
  id: '/bundle',
  path: '/bundle',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakfastRoute = BreakfastRouteImport.update({
  id: '/breakfast',
  path: '/breakfast',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R20MinuteMealRoute = R20MinuteMealRouteImport.update({
  id: '/20-minute-meal',
  path: '/20-minute-meal',
  getParentRoute: () => rootRouteImport,
} as any)
const R10MealBlueprintRoute = R10MealBlueprintRouteImport.update({
  id: '/10-meal-blueprint',
  path: '/10-meal-blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/10-meal-blueprint': typeof R10MealBlueprintRoute
  '/20-minute-meal': typeof R20MinuteMealRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/breakfast': typeof BreakfastRoute
  '/bundle': typeof BundleRoute
  '/cognitive-performance': typeof CognitivePerformanceRoute
  '/desserts': typeof DessertsRoute
  '/dinner': typeof DinnerRoute
  '/family-dinners': typeof FamilyDinnersRoute
  '/food-as-medicine': typeof FoodAsMedicineRoute
  '/free-recipes': typeof FreeRecipesRoute
  '/glp1': typeof Glp1Route
  '/gut-health': typeof GutHealthRoute
  '/gut-reset': typeof GutResetRoute
  '/home-old': typeof HomeOldRoute
  '/hormonal-health': typeof HormonalHealthRoute
  '/longevity': typeof LongevityRoute
  '/lunch': typeof LunchRoute
  '/mens-performance': typeof MensPerformanceRoute
  '/metabolic-health': typeof MetabolicHealthRoute
  '/metabolic-reset': typeof MetabolicResetRoute
  '/plant-based': typeof PlantBasedRoute
  '/real-food-reset': typeof RealFoodResetRoute
  '/smoothies': typeof SmoothiesRoute
  '/snacks': typeof SnacksRoute
  '/sunday-prep': typeof SundayPrepRoute
  '/system': typeof SystemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/10-meal-blueprint': typeof R10MealBlueprintRoute
  '/20-minute-meal': typeof R20MinuteMealRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/breakfast': typeof BreakfastRoute
  '/bundle': typeof BundleRoute
  '/cognitive-performance': typeof CognitivePerformanceRoute
  '/desserts': typeof DessertsRoute
  '/dinner': typeof DinnerRoute
  '/family-dinners': typeof FamilyDinnersRoute
  '/food-as-medicine': typeof FoodAsMedicineRoute
  '/free-recipes': typeof FreeRecipesRoute
  '/glp1': typeof Glp1Route
  '/gut-health': typeof GutHealthRoute
  '/gut-reset': typeof GutResetRoute
  '/home-old': typeof HomeOldRoute
  '/hormonal-health': typeof HormonalHealthRoute
  '/longevity': typeof LongevityRoute
  '/lunch': typeof LunchRoute
  '/mens-performance': typeof MensPerformanceRoute
  '/metabolic-health': typeof MetabolicHealthRoute
  '/metabolic-reset': typeof MetabolicResetRoute
  '/plant-based': typeof PlantBasedRoute
  '/real-food-reset': typeof RealFoodResetRoute
  '/smoothies': typeof SmoothiesRoute
  '/snacks': typeof SnacksRoute
  '/sunday-prep': typeof SundayPrepRoute
  '/system': typeof SystemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/10-meal-blueprint': typeof R10MealBlueprintRoute
  '/20-minute-meal': typeof R20MinuteMealRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/breakfast': typeof BreakfastRoute
  '/bundle': typeof BundleRoute
  '/cognitive-performance': typeof CognitivePerformanceRoute
  '/desserts': typeof DessertsRoute
  '/dinner': typeof DinnerRoute
  '/family-dinners': typeof FamilyDinnersRoute
  '/food-as-medicine': typeof FoodAsMedicineRoute
  '/free-recipes': typeof FreeRecipesRoute
  '/glp1': typeof Glp1Route
  '/gut-health': typeof GutHealthRoute
  '/gut-reset': typeof GutResetRoute
  '/home-old': typeof HomeOldRoute
  '/hormonal-health': typeof HormonalHealthRoute
  '/longevity': typeof LongevityRoute
  '/lunch': typeof LunchRoute
  '/mens-performance': typeof MensPerformanceRoute
  '/metabolic-health': typeof MetabolicHealthRoute
  '/metabolic-reset': typeof MetabolicResetRoute
  '/plant-based': typeof PlantBasedRoute
  '/real-food-reset': typeof RealFoodResetRoute
  '/smoothies': typeof SmoothiesRoute
  '/snacks': typeof SnacksRoute
  '/sunday-prep': typeof SundayPrepRoute
  '/system': typeof SystemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/10-meal-blueprint'
    | '/20-minute-meal'
    | '/about'
    | '/blog'
    | '/breakfast'
    | '/bundle'
    | '/cognitive-performance'
    | '/desserts'
    | '/dinner'
    | '/family-dinners'
    | '/food-as-medicine'
    | '/free-recipes'
    | '/glp1'
    | '/gut-health'
    | '/gut-reset'
    | '/home-old'
    | '/hormonal-health'
    | '/longevity'
    | '/lunch'
    | '/mens-performance'
    | '/metabolic-health'
    | '/metabolic-reset'
    | '/plant-based'
    | '/real-food-reset'
    | '/smoothies'
    | '/snacks'
    | '/sunday-prep'
    | '/system'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/10-meal-blueprint'
    | '/20-minute-meal'
    | '/about'
    | '/blog'
    | '/breakfast'
    | '/bundle'
    | '/cognitive-performance'
    | '/desserts'
    | '/dinner'
    | '/family-dinners'
    | '/food-as-medicine'
    | '/free-recipes'
    | '/glp1'
    | '/gut-health'
    | '/gut-reset'
    | '/home-old'
    | '/hormonal-health'
    | '/longevity'
    | '/lunch'
    | '/mens-performance'
    | '/metabolic-health'
    | '/metabolic-reset'
    | '/plant-based'
    | '/real-food-reset'
    | '/smoothies'
    | '/snacks'
    | '/sunday-prep'
    | '/system'
  id:
    | '__root__'
    | '/'
    | '/10-meal-blueprint'
    | '/20-minute-meal'
    | '/about'
    | '/blog'
    | '/breakfast'
    | '/bundle'
    | '/cognitive-performance'
    | '/desserts'
    | '/dinner'
    | '/family-dinners'
    | '/food-as-medicine'
    | '/free-recipes'
    | '/glp1'
    | '/gut-health'
    | '/gut-reset'
    | '/home-old'
    | '/hormonal-health'
    | '/longevity'
    | '/lunch'
    | '/mens-performance'
    | '/metabolic-health'
    | '/metabolic-reset'
    | '/plant-based'
    | '/real-food-reset'
    | '/smoothies'
    | '/snacks'
    | '/sunday-prep'
    | '/system'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R10MealBlueprintRoute: typeof R10MealBlueprintRoute
  R20MinuteMealRoute: typeof R20MinuteMealRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  BreakfastRoute: typeof BreakfastRoute
  BundleRoute: typeof BundleRoute
  CognitivePerformanceRoute: typeof CognitivePerformanceRoute
  DessertsRoute: typeof DessertsRoute
  DinnerRoute: typeof DinnerRoute
  FamilyDinnersRoute: typeof FamilyDinnersRoute
  FoodAsMedicineRoute: typeof FoodAsMedicineRoute
  FreeRecipesRoute: typeof FreeRecipesRoute
  Glp1Route: typeof Glp1Route
  GutHealthRoute: typeof GutHealthRoute
  GutResetRoute: typeof GutResetRoute
  HomeOldRoute: typeof HomeOldRoute
  HormonalHealthRoute: typeof HormonalHealthRoute
  LongevityRoute: typeof LongevityRoute
  LunchRoute: typeof LunchRoute
  MensPerformanceRoute: typeof MensPerformanceRoute
  MetabolicHealthRoute: typeof MetabolicHealthRoute
  MetabolicResetRoute: typeof MetabolicResetRoute
  PlantBasedRoute: typeof PlantBasedRoute
  RealFoodResetRoute: typeof RealFoodResetRoute
  SmoothiesRoute: typeof SmoothiesRoute
  SnacksRoute: typeof SnacksRoute
  SundayPrepRoute: typeof SundayPrepRoute
  SystemRoute: typeof SystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sunday-prep': {
      id: '/sunday-prep'
      path: '/sunday-prep'
      fullPath: '/sunday-prep'
      preLoaderRoute: typeof SundayPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snacks': {
      id: '/snacks'
      path: '/snacks'
      fullPath: '/snacks'
      preLoaderRoute: typeof SnacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smoothies': {
      id: '/smoothies'
      path: '/smoothies'
      fullPath: '/smoothies'
      preLoaderRoute: typeof SmoothiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-food-reset': {
      id: '/real-food-reset'
      path: '/real-food-reset'
      fullPath: '/real-food-reset'
      preLoaderRoute: typeof RealFoodResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plant-based': {
      id: '/plant-based'
      path: '/plant-based'
      fullPath: '/plant-based'
      preLoaderRoute: typeof PlantBasedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metabolic-reset': {
      id: '/metabolic-reset'
      path: '/metabolic-reset'
      fullPath: '/metabolic-reset'
      preLoaderRoute: typeof MetabolicResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metabolic-health': {
      id: '/metabolic-health'
      path: '/metabolic-health'
      fullPath: '/metabolic-health'
      preLoaderRoute: typeof MetabolicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mens-performance': {
      id: '/mens-performance'
      path: '/mens-performance'
      fullPath: '/mens-performance'
      preLoaderRoute: typeof MensPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lunch': {
      id: '/lunch'
      path: '/lunch'
      fullPath: '/lunch'
      preLoaderRoute: typeof LunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/longevity': {
      id: '/longevity'
      path: '/longevity'
      fullPath: '/longevity'
      preLoaderRoute: typeof LongevityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hormonal-health': {
      id: '/hormonal-health'
      path: '/hormonal-health'
      fullPath: '/hormonal-health'
      preLoaderRoute: typeof HormonalHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-old': {
      id: '/home-old'
      path: '/home-old'
      fullPath: '/home-old'
      preLoaderRoute: typeof HomeOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gut-reset': {
      id: '/gut-reset'
      path: '/gut-reset'
      fullPath: '/gut-reset'
      preLoaderRoute: typeof GutResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gut-health': {
      id: '/gut-health'
      path: '/gut-health'
      fullPath: '/gut-health'
      preLoaderRoute: typeof GutHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glp1': {
      id: '/glp1'
      path: '/glp1'
      fullPath: '/glp1'
      preLoaderRoute: typeof Glp1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-recipes': {
      id: '/free-recipes'
      path: '/free-recipes'
      fullPath: '/free-recipes'
      preLoaderRoute: typeof FreeRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-as-medicine': {
      id: '/food-as-medicine'
      path: '/food-as-medicine'
      fullPath: '/food-as-medicine'
      preLoaderRoute: typeof FoodAsMedicineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-dinners': {
      id: '/family-dinners'
      path: '/family-dinners'
      fullPath: '/family-dinners'
      preLoaderRoute: typeof FamilyDinnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dinner': {
      id: '/dinner'
      path: '/dinner'
      fullPath: '/dinner'
      preLoaderRoute: typeof DinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desserts': {
      id: '/desserts'
      path: '/desserts'
      fullPath: '/desserts'
      preLoaderRoute: typeof DessertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cognitive-performance': {
      id: '/cognitive-performance'
      path: '/cognitive-performance'
      fullPath: '/cognitive-performance'
      preLoaderRoute: typeof CognitivePerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundle': {
      id: '/bundle'
      path: '/bundle'
      fullPath: '/bundle'
      preLoaderRoute: typeof BundleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breakfast': {
      id: '/breakfast'
      path: '/breakfast'
      fullPath: '/breakfast'
      preLoaderRoute: typeof BreakfastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/20-minute-meal': {
      id: '/20-minute-meal'
      path: '/20-minute-meal'
      fullPath: '/20-minute-meal'
      preLoaderRoute: typeof R20MinuteMealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/10-meal-blueprint': {
      id: '/10-meal-blueprint'
      path: '/10-meal-blueprint'
      fullPath: '/10-meal-blueprint'
      preLoaderRoute: typeof R10MealBlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R10MealBlueprintRoute: R10MealBlueprintRoute,
  R20MinuteMealRoute: R20MinuteMealRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  BreakfastRoute: BreakfastRoute,
  BundleRoute: BundleRoute,
  CognitivePerformanceRoute: CognitivePerformanceRoute,
  DessertsRoute: DessertsRoute,
  DinnerRoute: DinnerRoute,
  FamilyDinnersRoute: FamilyDinnersRoute,
  FoodAsMedicineRoute: FoodAsMedicineRoute,
  FreeRecipesRoute: FreeRecipesRoute,
  Glp1Route: Glp1Route,
  GutHealthRoute: GutHealthRoute,
  GutResetRoute: GutResetRoute,
  HomeOldRoute: HomeOldRoute,
  HormonalHealthRoute: HormonalHealthRoute,
  LongevityRoute: LongevityRoute,
  LunchRoute: LunchRoute,
  MensPerformanceRoute: MensPerformanceRoute,
  MetabolicHealthRoute: MetabolicHealthRoute,
  MetabolicResetRoute: MetabolicResetRoute,
  PlantBasedRoute: PlantBasedRoute,
  RealFoodResetRoute: RealFoodResetRoute,
  SmoothiesRoute: SmoothiesRoute,
  SnacksRoute: SnacksRoute,
  SundayPrepRoute: SundayPrepRoute,
  SystemRoute: SystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
